### ISSUE TITLE
word filters

### ISSUE THREAD

**Issue by princejoogie** [omsimos/umamin#90]
![image](https://user-images.githubusercontent.com/47204120/182426004-adfdf283-dac5-49dd-b7fa-6917d48d32b6.png)

word filters
- per user? list of words to ban
- app-level filter (sentiment analysis?)

**Comment by jdpena28** [comment]
I have thoughts here @princejoogie can we have like option per user to opt in or opt out for explicit messages ELSE if the integrity of the app is not being a wholesome umamin app 😅.

**Comment by princejoogie** [comment]
> I have thoughts here @princejoogie can we have like option per user to opt in or opt out for explicit messages ELSE if the integrity of the app is not being a wholesome umamin app 😅. 

yupps, users will be able to add a list of words they want to filter so its per user

**Comment by jdpena28** [comment]
Oh I seee that's the bullet one right ?, They are the one who will choice what words to be block.

**Comment by edmer664** [comment]
this might do the job lol...
https://www.npmjs.com/package/bad-words
